# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MHTableView’ do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for MHTableView

end


platform :ios, '8.0'
pod 'MJRefresh', '~> 3.1.0’
pod 'AFNetworking'
pod 'YYModel'
pod 'iRate', '~> 1.11.3'
pod 'Reachability',  '~> 3.0.0'
pod 'XHImageViewer', '~> 0.1.2'
pod 'SDWebImage', '~> 3.7.2'
pod 'SVWebViewController', '~> 1.0'
pod 'SDAutoLayout', '~> 1.52'
pod 'FDFullscreenPopGesture', '1.1'
pod 'IQKeyboardManager', '~> 3.3.6'
pod 'AvoidCrash'
pod 'NullSafe'
pod 'DZNEmptyDataSet' #tableView 没数据时提示页面
pod 'SVProgressHUD', '~> 2.0.3'

